# Generated by Django 3.0.1 on 2020-01-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0003_auto_20200101_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_method",
            field=models.CharField(
                choices=[
                    ("e", "e-mail"),
                    ("p", "Phone"),
                    ("t", "Text"),
                    ("i", "In-person"),
                    ("l", "Letter"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="ground_rules",
            field=models.CharField(
                choices=[
                    ("otr", "On-the-record"),
                    ("bg", "On background"),
                    ("db", "Deep Background"),
                    ("or", "Off-the-record"),
                ],
                default="otr",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="foia_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="FOIA e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
