# Generated by Django 3.0.1 on 2020-01-01 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0005_auto_20200101_1355"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttask",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="task_started",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
