# Generated by Django 3.0.1 on 2020-01-01 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0006_auto_20200101_1401"),
    ]

    operations = [
        migrations.AddField(
            model_name="foiarequest",
            name="short_description",
            field=models.CharField(default="Unspecified", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="foiarequest",
            name="date_filed",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
