# Generated by Django 3.0.1 on 2020-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0007_auto_20200101_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="foiarequest",
            name="time_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
