# Generated by Django 3.0.1 on 2020-01-02 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0008_foiarequest_time_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="publication_date",
            field=models.DateField(default=datetime.date(2020, 1, 2)),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("db", "Database administrator"),
                    ("rp", "Person affected (anecdotal source)"),
                    ("e", "Expert"),
                    ("pr", "Spokesperson, PR-Rep"),
                    ("f", "Public Records officer"),
                    ("o", "Public/Company official"),
                    ("i", "Company or business employee (current or former)"),
                ],
                max_length=2,
            ),
        ),
    ]
