# Generated by Django 3.0.1 on 2020-01-02 02:42

from django.db import migrations, models
import sourcebook.models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0009_auto_20200101_2140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="publication_date",
            field=models.DateField(default=sourcebook.models.get_current_date),
        ),
    ]
