# Generated by Django 3.0.1 on 2020-01-02 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0010_auto_20200101_2142"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="is_public_body",
            field=models.BooleanField(default=False, verbose_name="Public Body?"),
        ),
        migrations.AlterField(
            model_name="document",
            name="foia_request",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sourcebook.FoiaRequest",
                verbose_name="FOIA Request",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="is_federal",
            field=models.BooleanField(default=False, verbose_name="Federal Agency?"),
        ),
    ]
