# Generated by Django 3.0.1 on 2020-01-02 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0011_auto_20200101_2149"),
    ]

    operations = [
        migrations.AddField(
            model_name="foiarequest",
            name="related_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sourcebook.Project",
            ),
        ),
    ]
