# Generated by Django 3.0.1 on 2020-01-02 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0012_foiarequest_related_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="related_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sourcebook.Project",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="related_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sourcebook.Project",
            ),
        ),
    ]
