# Generated by Django 3.0.2 on 2020-01-02 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sourcebook.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("sourcebook", "0013_auto_20200101_2157"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoiaRequestBase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.CharField(max_length=100)),
                ("date_filed", models.DateTimeField(default=django.utils.timezone.now)),
                ("requested_records", models.TextField()),
                (
                    "expedited_processing",
                    models.TextField(
                        blank=True,
                        verbose_name="justification for expedited processing",
                    ),
                ),
                (
                    "fee_waiver",
                    models.TextField(
                        blank=True, verbose_name="fee waiver justification"
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sourcebook.Project",
                    ),
                ),
                (
                    "requested_formats",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Requested Format",
                    ),
                ),
            ],
            options={"verbose_name": "Base FOIA Request",},
        ),
        migrations.AddField(
            model_name="state",
            name="public_records_act_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="name of state public records act",
            ),
        ),
        migrations.CreateModel(
            name="FoiaRequestItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=150, verbose_name="name of public records officer"
                    ),
                ),
                (
                    "date_filed",
                    models.DateField(default=sourcebook.models.get_current_date),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nr", "no response"),
                            ("a", "acknowledged"),
                            ("cf", "closed - no redactions"),
                            ("cr", "closed - some redactions"),
                            ("ce", "closed - did not pay fee"),
                            ("ap", "appealed"),
                            ("s", "sued"),
                        ],
                        default="nr",
                        max_length=2,
                    ),
                ),
                (
                    "fee_assessed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "modified_request",
                    models.BooleanField(
                        default=False,
                        help_text="Have you modified (narrowed or broadened) your initial request?",
                    ),
                ),
                ("time_completed", models.DateField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sourcebook.Entity",
                    ),
                ),
                (
                    "request_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sourcebook.FoiaRequestBase",
                    ),
                ),
            ],
            options={"verbose_name": "FOIA Request",},
        ),
    ]
