# Generated by Django 3.0.2 on 2020-01-02 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0014_auto_20200102_1103"),
    ]

    operations = [
        migrations.RemoveField(model_name="foiarequestitem", name="date_filed",),
        migrations.RemoveField(model_name="foiarequestitem", name="modified_request",),
        migrations.AddField(
            model_name="foiarequestitem",
            name="expedited_processing_granted",
            field=models.BooleanField(
                default=False,
                help_text="Did the agency grant your request for expedited processing?",
            ),
        ),
        migrations.AddField(
            model_name="foiarequestitem",
            name="modifications",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                default=[],
                help_text="list any modifications you've made to your original request",
                size=None,
            ),
        ),
    ]
