# Generated by Django 3.0.2 on 2020-01-02 16:55

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0017_auto_20200102_1151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiarequestitem",
            name="modifications",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="list any modifications you've made to your original request",
                null=True,
                size=None,
            ),
        ),
    ]
