# Generated by Django 3.0.2 on 2020-01-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0018_auto_20200102_1155"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foiarequestbase",
            options={
                "verbose_name": "FOIA Request Body",
                "verbose_name_plural": "FOIA Request Bodies",
            },
        ),
        migrations.AlterModelOptions(
            name="foiarequestitem", options={"verbose_name": "FOIA Request"},
        ),
        migrations.AlterField(
            model_name="document",
            name="foia_request",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sourcebook.FoiaRequestItem",
                verbose_name="FOIA Request",
            ),
        ),
        migrations.DeleteModel(name="FoiaRequest",),
    ]
