# Generated by Django 3.0.2 on 2020-01-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0019_auto_20200102_1204"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="foia_request",
            new_name="foia_request_item",
        ),
    ]
