# Generated by Django 3.0.2 on 2020-01-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0020_auto_20200102_1208"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="foia_request_item",),
        migrations.AddField(
            model_name="document",
            name="foia_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sourcebook.FoiaRequestItem",
                verbose_name="FOIA Request",
            ),
        ),
    ]
