# Generated by Django 3.0.2 on 2020-01-03 16:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("sourcebook", "0021_auto_20200102_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiarequestbase",
            name="requested_formats",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Requested format",
            ),
        ),
    ]
