# Generated by Django 3.0.2 on 2020-01-03 17:08

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("sourcebook", "0022_auto_20200103_1146"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledFoiaContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.CharField(max_length=100)),
                ("requested_records", models.TextField()),
                (
                    "expedited_processing",
                    models.TextField(
                        blank=True,
                        verbose_name="justification for expedited processing",
                    ),
                ),
                (
                    "fee_waiver",
                    models.TextField(
                        blank=True, verbose_name="fee waiver justification"
                    ),
                ),
                ("date_started", models.DateField(auto_now_add=True)),
                (
                    "date_stopped",
                    models.DateField(
                        blank=True,
                        help_text="When do you want to stop running this scheduler?",
                        null=True,
                    ),
                ),
                (
                    "request_frequency",
                    models.DurationField(
                        help_text="How frequently do you want to have this request filed?"
                    ),
                ),
                (
                    "request_period",
                    models.BooleanField(
                        verbose_name="Have request go out to all records filed since the last time you ran the request"
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sourcebook.Project",
                    ),
                ),
                (
                    "requested_formats",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Requested format",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ScheduledFoiaAgency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=150, verbose_name="name of public records officer"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sourcebook.Entity",
                    ),
                ),
                (
                    "request_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sourcebook.ScheduledFoiaContent",
                    ),
                ),
            ],
        ),
    ]
