# Generated by Django 3.0.2 on 2020-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0023_scheduledfoiaagency_scheduledfoiacontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiarequestitem",
            name="recipient_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="name of public records officer",
            ),
        ),
    ]
