# Generated by Django 3.0.2 on 2020-01-07 08:05
# basically unmodified from http://logan.tw/posts/2017/12/30/full-text-search-with-django-and-postgresql/
# (i.e. only changes are to project-specific tables, etc.)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0026_auto_20200107_0258"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER foiarequestbase_update_trigger
            BEFORE INSERT OR UPDATE OF short_description, requested_records, expedited_processing, search_vector
            ON sourcebook_foiarequestbase
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', short_description, requested_records, expedited_processing
            );

            UPDATE sourcebook_foiarequestbase SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS foiarequestbase_update_trigger
            ON sourcebook_foiarequestbase;
            """,
        )
    ]
