# Generated by Django 3.0.2 on 2020-01-31 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcebook', '0027_create_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foiarequestbase',
            options={'ordering': ('-date_filed',), 'verbose_name': 'FOIA Request Body', 'verbose_name_plural': 'FOIA Request Bodies'},
        ),
        migrations.AlterField(
            model_name='foiarequestitem',
            name='request_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foia_requests', to='sourcebook.FoiaRequestBase'),
        ),
    ]
