# Generated by Django 3.0.2 on 2020-02-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0028_auto_20200131_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="gender",
            field=models.CharField(
                choices=[
                    ("m", "Man"),
                    ("w", "Woman"),
                    ("n", "Nonconforming"),
                    ("i", "N/A"),
                    ("u", "Unknown"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="race",
            field=models.CharField(
                choices=[
                    ("poc", "Person of color"),
                    ("w", "White"),
                    ("na", "N/A"),
                    ("unk", "Unknown"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("db", "Database administrator"),
                    ("rp", "Person affected (anecdotal source)"),
                    ("e", "Expert"),
                    ("pr", "Spokesperson, PR-Rep"),
                    ("f", "Public Records Officer"),
                    ("o", "Public/Company Official"),
                    ("i", "Company or business employee (current or former)"),
                    ("mn", "General Inbox (e.g. Media Relations number)"),
                ],
                max_length=2,
            ),
        ),
    ]
