# Generated by Django 3.0.2 on 2020-02-16 07:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0030_auto_20200212_0323"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="source",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="sourcebook__search__3ffe9d_gin"
            ),
        ),
    ]
