# Generated by Django 3.0.2 on 2020-02-16 07:20
# From http://logan.tw/posts/2017/12/30/full-text-search-with-django-and-postgresql/
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcebook', '0031_auto_20200216_0220'),
    ]

    operations = [
         migrations.RunSQL(
            sql="""
            CREATE TRIGGER source_update_trigger
            BEFORE INSERT OR UPDATE OF first_name, last_name, title, home_number, cell_number, work_number, email, twitter, search_vector
            ON sourcebook_source
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', first_name, last_name, title, home_number, cell_number, work_number, email, twitter
            );

            UPDATE sourcebook_source SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS source_update_trigger
            ON sourcebook_source;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER entity_update_trigger
            BEFORE INSERT OR UPDATE OF name, municipality, locality, zip_code, foia_email, search_vector
            ON sourcebook_entity
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', name, municipality, locality, zip_code, foia_email
            );

            UPDATE sourcebook_entity SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS entity_update_trigger
            ON sourcebook_entity;
            """,
        ),
    ]
