# Generated by Django 3.0.3 on 2020-02-17 18:17

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0032_create_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
