# Generated by Django 3.0.3 on 2020-02-17 18:18

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0033_auto_20200217_1317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
