# Generated by Django 3.0.3 on 2020-02-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0034_auto_20200217_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
