# Generated by Django 3.0.3 on 2020-02-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sourcebook", "0035_auto_20200217_1448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiarequestitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("nr", "no response"),
                    ("a", "acknowledged"),
                    ("cf", "closed - no redactions"),
                    ("cr", "closed - some redactions"),
                    ("ce", "closed - did not pay fee"),
                    ("ap", "appealed"),
                    ("s", "sued"),
                    ("cn", "closed - no records"),
                ],
                default="nr",
                max_length=2,
            ),
        ),
    ]
